Update for core22 migration
snapcrafters/mattermost-desktop pull request #56
Opened 2022-07-25 15:44 UTC by jnsgruk

This PR updates `snapcraft.yaml` for `core22` and builds with Snapcraft `7.1.0`+.

Right now, there is a bug in the `dump` plugin, so I've overridden it. Snap builds fine, still need to test on a VM.

2022-07-25 15:55 UTC, jnsgruk commented
It works!

![image](https://user-images.githubusercontent.com/668505/180821919-32fb99d3-5e6c-4b07-a29d-4aa233109444.png)

2022-07-25 16:31 UTC, kenvandine requested changes
The cleanup part should reference gnome-42-2204 rather than gnome-42-2204-sdk.. Technically both should work, but gnome-42-2204 is correct.

2022-07-25 16:34 UTC, jnsgruk commented
> The cleanup part should reference gnome-42-2204 rather than gnome-42-2204-sdk.. Technically both should work, but gnome-42-2204 is correct.

Done! Thanks! :+1:

2022-08-05 12:27 UTC, jnsgruk commented
@diddledani @kenvandine I think this is good to merge now! Snapcraft 7.1.1 is in stable :)

2022-08-05 12:32 UTC, kenvandine approved these changes

2022-08-05 12:32 UTC, merged