Add a sync-release action to automate updating to the latest release
snapcrafters/mattermost-desktop pull request #70
Opened 2023-01-09 17:54 UTC by kenvandine

2023-01-09 17:57 UTC, diddledani commented on .github/workflows/sync-release.yml
> +          git config --global user.email 'ken@vandine.org'
I think these should probably be generic snap crafters name and email?

2023-01-10 23:37 UTC, merlijn-sebrechts commented
I created the stable branch environment and added the snapcrafters-bot commit token to it.

Please update the actions to use this environment and please add the tokens as described here: https://forum.snapcraft.io/t/automatic-snap-refreshes-using-github-actions-snapcrafters-guide/33444

(also note I changed some of the names of the tokens, so make sure to update them in your actions as well)

2023-10-08 18:48 UTC, merlijn-sebrechts requested changes
@kenvandine can you update from the latest `signal-desktop` actions?

2023-11-14 09:27 UTC, jnsgruk commented
Closing in favour of #81

2023-11-14 09:27 UTC, closed without merging